"""Workspace domain contracts."""

from prp_runtime.workspace.backend import (
    DirectoryEntry,
    FileReadResult,
    WorkspaceBackend,
    WorkspaceBackendError,
    WorkspaceBackendProtocol,
)
from prp_runtime.workspace.changes import (
    ChangeSet,
    ChangeSetId,
    FileChange,
    FileChangeAction,
    FileContent,
    Patch,
    new_change_set_id,
)
from prp_runtime.workspace.isolation import (
    BaseSnapshot,
    ExecutionSlot,
    IsolationBackend,
    IsolationCapacityError,
    IsolationError,
    IsolationLeaseError,
    IsolationOwnershipError,
    LocalIsolationBackend,
    SlotStatus,
)
from prp_runtime.workspace.models import (
    Snapshot,
    SnapshotEntry,
    SnapshotEntryType,
    SnapshotManifest,
    SnapshotStatus,
    Workspace,
    WorkspaceRoot,
    WorkspaceRootMapping,
    WorkspaceSource,
    WorkspaceSourceType,
    WorkspaceStatus,
)
from prp_runtime.workspace.local import LocalWorkspaceHandle, resolve_local_workspace
from prp_runtime.workspace.resolver import (
    ResolvedWorkspace,
    WorkspaceResolveError,
    WorkspaceResolver,
)
from prp_runtime.workspace.sandbox import (
    BubblewrapBackend,
    SandboxBackend,
    SandboxCapabilities,
    SandboxExecutionError,
    SandboxUnavailableError,
    build_bwrap_argv,
    default_runtime_roots,
    parse_bwrap_version,
    probe_bwrap,
    require_sandbox,
)

__all__ = [
    "ChangeSet",
    "ChangeSetId",
    "DirectoryEntry",
    "FileReadResult",
    "FileChange",
    "FileChangeAction",
    "FileContent",
    "Patch",
    "new_change_set_id",
    "Snapshot",
    "SnapshotEntry",
    "SnapshotEntryType",
    "SnapshotManifest",
    "SnapshotStatus",
    "Workspace",
    "WorkspaceRoot",
    "WorkspaceRootMapping",
    "WorkspaceBackend",
    "WorkspaceBackendError",
    "WorkspaceBackendProtocol",
    "WorkspaceSource",
    "WorkspaceSourceType",
    "WorkspaceStatus",
    "LocalWorkspaceHandle",
    "ResolvedWorkspace",
    "WorkspaceResolveError",
    "WorkspaceResolver",
    "resolve_local_workspace",
    "BaseSnapshot",
    "ExecutionSlot",
    "IsolationBackend",
    "IsolationCapacityError",
    "IsolationError",
    "IsolationLeaseError",
    "IsolationOwnershipError",
    "LocalIsolationBackend",
    "SlotStatus",
    "BubblewrapBackend",
    "SandboxBackend",
    "SandboxCapabilities",
    "SandboxExecutionError",
    "SandboxUnavailableError",
    "build_bwrap_argv",
    "default_runtime_roots",
    "parse_bwrap_version",
    "probe_bwrap",
    "require_sandbox",
]
